### ISSUE TITLE
setup cluster monitoring / logging / alerts - either using self-hosted Prometheus or using AWS services

### ISSUE THREAD

**Issue by OriHoch** [ViderumGlobal/ckan-cloud-cluster#4]

**Comment by akariv** [comment]
Preference to use Google services, need to understand exactly how we're going to use them.

**Comment by zelima** [comment]
I've setup dashboard for cluster monitoring here https://app.google.stackdriver.com/dashboards/11874264311182482851?project=ckan-cloud

**Comment by OriHoch** [comment]
monitor / alerts docs: https://github.com/ViderumGlobal/ckan-cloud-operator/blob/master/docs/MONITORING.md

Using:
* Prometheus Alertmanager for general infrastructure alerts
* Jenkins periodical task which check app and related infra. readyness
