### ISSUE TITLE
setup Heptio ARK on the cluster for continuous backups of the Kubernetes configurations and persistent storage

### ISSUE THREAD

**Issue by OriHoch** [ViderumGlobal/ckan-cloud-cluster#7]
child of ViderumGlobal/PM#5

**Comment by zelima** [comment]
I've setup the backups server following their tutorial https://github.com/heptio/velero/blob/master/docs/gcp-config.md

Few things to mention:
- buckets are named `cluster-backups-{ENV}`
- For I've created a new service account  backup-edge@ckan-cloud.iam.gserviceaccount.com and gave the permissions below. Probably we will need to give that permission to `ckan-cloud-{ENV}-operator` instead (role name is velero.server)
```
ROLE_PERMISSIONS=(
    compute.disks.get
    compute.disks.create
    compute.disks.createSnapshot
    compute.snapshots.get
    compute.snapshots.create
    compute.snapshots.useReadOnly
    compute.snapshots.delete
    compute.zones.get
)
```
- secrets are named as in tutorial `credentials-velero`
- Created under `heptio-ark` namspace (probably worht to move to `backups` or similar)
- ATM schedules are run daily, `ark schedule create cluster-backup --schedule "0 0 * * *"`
  - backup names are `cluster-backup`

**Comment by zelima** [comment]
I've setup the backups server following their tutorial https://github.com/heptio/velero/blob/master/docs/gcp-config.md

Few things to mention:
- buckets are named `cluster-backups-{ENV}`
- For now I've created a new service account  backup-edge@ckan-cloud.iam.gserviceaccount.com and gave the permissions below. Probably we will need to give that permission to `ckan-cloud-{ENV}-operator` instead (role name is velero.server)
```
ROLE_PERMISSIONS=(
    compute.disks.get
    compute.disks.create
    compute.disks.createSnapshot
    compute.snapshots.get
    compute.snapshots.create
    compute.snapshots.useReadOnly
    compute.snapshots.delete
    compute.zones.get
)
```
- secrets are named as in tutorial `credentials-velero`
- Created under `heptio-ark` namspace (probably worht to move to `backups` or similar)
- ATM schedules are run daily, `ark schedule create cluster-backup --schedule "0 0 * * *"`
  - backup names are `cluster-backup`

**Comment by zelima** [comment]
Volume snapshots are created, from  `ark-backup.json`:

```
"status": {
"version": 1,
"expiration": "2019-03-28T06:35:09Z",
"phase": "Completed",
"validationErrors": null,
"startTimestamp": "2019-02-26T06:35:09Z",
"completionTimestamp": "2019-02-26T06:37:29Z",
"volumeSnapshotsAttempted": 1,
"volumeSnapshotsCompleted": 1
}
```
